export const allproduit=[
    {id:1,imag:'../puctures/cust1.png',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:2,imag:'../puctures/cust2.png',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:3,imag:'../puctures/cust3.png',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:4,imag:'../puctures/cust4.png',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:5,imag:'../puctures/desk1.png',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:6,imag:'../puctures/desk2.png',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:7,imag:'../puctures/desk3.png',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:8,imag:'../puctures/desk4.png',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:9,imag:'../puctures/monitor1.png',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:10,imag:'../puctures/monitor1.png',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:11,imag:'../puctures/monitor2.png',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:12,imag:'../puctures/monitor3.png',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:13,imag:'../puctures/iapad1.jpeg',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:14,imag:'../puctures/iapad2.jpeg',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:15,imag:'../puctures/iapad3.jpeg',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:16,imag:'../puctures/iapad4.jpeg',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:17,imag:'../puctures/IMG1.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1,reference:'549860 0DELL'},
    {id:18,imag:'../puctures/img3.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:19,imag:'../puctures/img4.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:20,imag:'../puctures/IMG1.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:21,imag:'../puctures/IMG1.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:22,imag:'../puctures/IMG1.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:23,imag:'../puctures/IMG1.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:24,imag:'../puctures/img3.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:25,imag:'../puctures/img4.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:26,imag:'../puctures/IMG1.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:27,imag:'../puctures/IMG1.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:28,imag:'../puctures/IMG1.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:29,imag:'../puctures/IMG1.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:30,imag:'../puctures/img3.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:31,imag:'../puctures/img4.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:32,imag:'../puctures/IMG1.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:33,imag:'../puctures/IMG1.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:34,imag:'../puctures/IMG1.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:35,imag:'../puctures/IMG1.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:36,imag:'../puctures/IMG1.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:37,imag:'../puctures/IMG1.jpeg',price:250,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:38,imag:'../puctures/IMG1.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}, 
    {id:39,imag:'../puctures/IMG1.jpeg',price:300,insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1}
    ,{id:40,imag:'../puctures/redmi1.jpeg',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:41,imag:'../puctures/redmi2.jpeg',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:42,imag:'../puctures/redmi3.jpeg',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:43,imag:'../puctures/redmi4.jpeg',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:44,imag:'../puctures/sumsung1.jpeg',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:45,imag:'../puctures/sumsung2.jpeg',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:46,imag:'../puctures/sumsung3.jpeg',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:47,imag:'../puctures/sumsung4.jpeg',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:50,imag:'../puctures/sumsung1.jpeg',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:51,imag:'../puctures/img4.jpeg',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:52,imag:'../puctures/desk2.png',price:300,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:60,quantiter:1},
    {id:53,imag:'../puctures/cust1.png',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},
    {id:54,imag:'../puctures/redmi1.jpeg',price:250,revieus:'../puctures/Star 9.png',revieusin:'../puctures/Star 1.png',insc:'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',nomber_darticle:500,quantiter:1},    
]